### ISSUE TITLE
Exchange/Fiat On-ramp Buttons

### ISSUE THREAD

**Issue by Brian7786** [thenanocenter/getting-started#3]
Could we add 4 buttons (in the same fashion as the wallets are) for exchange/fiat on-ramp options for people to buy Nano?  We don't need to have referral links by any means but I think explanation on how to buy while they're on this page would be helpful to be included.  

My thoughts (in this order, let's just keep the 3 for now I think for spacing.)
Binance  Yellow, Emblem/Binance (word itself)
Kucoin soft white, blue kucoin emblem
Nanex black, emblem

**Comment by guil5566** [comment]
I would suggest at least hiperlinks for the exchanges, but buttons would be more user friendly I guess
